name: CI
on: [push]
jobs:
  build:
    name: Build and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['18.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Test
        run: npm test --ci --coverage --maxWorkers=2

      - name: Build
        run: npm run build

      - name: Notify on failure
        if: failure()
        uses: slackapi/slack-github-action@v1.22.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "attachments": [
                {
                  "text": ":boom: CI failed for <https://www.npmjs.com/package/@terran-one/cosmwasm-vm-js|cosmwasm-vm-js>",
                  "color": "danger"
                }
              ]
            }
